### ISSUE TITLE
Show changes info

### ISSUE THREAD

**Issue by techtonik** [pyupio/pyup#22]
It would be awesome if it could show changelog information.

**Comment by luzfcb** [comment]
https://github.com/pyupio/pyup/blob/master/HISTORY.rst

**Comment by techtonik** [comment]
Just one of the history formats. Need a parser for them (with tests?).

**Comment by jayfk** [comment]
Yes, that'd great. 

I've started to work on a collection of changelogs for python packages at changelogs.net, e.g. for requests: https://changelogs.net/requests/

I thought about adding an API on top of that where everyone can query for changelogs for a given python package.

I'm not very happy with the results so far, this needs a lot of work unfortunately.

**Comment by techtonik** [comment]
@atodorov at @difio used a pretty interesting way of just diffing the changelogs between releases, so detecting a release and changelog location within it might be easier than writing dedicated parsers.

**Comment by atodorov** [comment]
@jayfk this is how it looked:
http://d3h3t4beeg8ypi.cloudfront.net/static/v57/i/f/b/changelog.png

if you want to go this route I can give you pointers around my code.

**Comment by techtonik** [comment]
@atodorov if not license mismatch, the code could probably be directly pulled in. =)

**Comment by jayfk** [comment]
> @jayfk this is how it looked:
> http://d3h3t4beeg8ypi.cloudfront.net/static/v57/i/f/b/changelog.png
> 
> if you want to go this route I can give you pointers around my code.

Thanks, I'll take a look at this soon!

**Comment by svetlyak40wt** [comment]
@jayfk @techtonik @atodorov I'm working on AllMyChanges.com – sophisticated release notes parser and subscription service. It would be wonderful to have integration with pyupio.

However, the problem is that in some cases changelog discovery and parsing require manual tuning and releases for some libraries can't be discovered automatically.

But anyway, fetching release notes through API greatly improve pull requests, created by pyup.

**Comment by techtonik** [comment]
@svetlyak40wt I am more interested to aggregate changes and read about them from the web. https://github.com/difio/difio was a good start, but it is dead, because economy doesn't support such initiatives.

**Comment by jayfk** [comment]
@svetlyak40wt AllMyChanges.com is great. I saw this a while ago (on HN I believe?).

I think what we really need - and I mean the open source community in general - is a place to store changelogs so that they are accessible by anyone.

Maybe wikidata? Something running on ethereum? A public git repo?

**Comment by svetlyak40wt** [comment]
@jayfk it is impossible to force everyone to use one place for their changelogs data. It is like building another babylon tower. There GitHub Releases, but I saw only few developers who use them consistently. Another project which tries to go this way is http://changehub.io, but it does not look alive.

That is why allmychanges tries to be language and source agnostic. It just collects information from different sources – plain texts, html pages, github releases, commit messages. Normalises it and makes available on the web, in emails and chats.

So, I don't belive in "one place" for everyone.

**Comment by svetlyak40wt** [comment]
@techtonik probably, my project is what are you looking for, it aggregates release notes info from different sources (see my previous comment) and makes them available on web, email, slack or via webhooks.

Also, you can tag versions you are using on different projects and to check if updates are available and read fresh release notes.

There isn't any economy in allmychanges (yet), because it is a pet-project and a tool I'm making for myself. But probably, I'll make an enterprise edition some day :)

**Comment by jayfk** [comment]
> @jayfk it is impossible to force everyone to use one place for their changelogs data. It is like building another babylon tower.

That's absolutely true and wasn't my intention. I don't want to force developers to use a specific system, I want *us* to build a collection of parsed changelogs and make it accessible for everyone.

The idea is to build a open database in a combined effort and use the data in whatever service we want. This way allmychanges, pyup, changelogs.net, requires.io, libraries.io etc. etc. could use it.

I don't know if this will ever happen, but if there are enough people interested in something like this, why not?

**Comment by svetlyak40wt** [comment]
@jayfk my service is already such collection. Everybody is free to add any changelogs into AllMyChanges. And they will be updated automatically.

Try to paste url of some project (from github, for example) into a search bar at allmychanges. It will try to find a changelog in repository or GH Releases, or build it from commits. If you'd like the result, it can be saved and made available to other people. You even don't need to register at the service.

**Comment by techtonik** [comment]
> I want us to build a collection of parsed changelogs and make it accessible for everyone.

I want to see a collection of changelog parsers with tests.
