### ISSUE TITLE
pyup wrongly thinks that `scp` is not Python 3 compatible

### ISSUE THREAD

**Issue by adamtheturtle** [pyupio/pyup#269]
Hi, thanks for the software.

I am a user of pyup and [`scp`](https://pypi.python.org/pypi/scp).

pyup shows that scp is not Python 3 compatible, but this is not correct.
[The test suite is run on Python 3](https://github.com/jbardin/scp.py/blob/master/.travis.yml#L7).
[`setup.py`](https://github.com/jbardin/scp.py/blob/master/setup.py#L35) shows "Programming Language :: Python :: 3.5". 

What needs to change to get  recognised as Python 3 compatible?

<img width="673" alt="screen shot 2018-01-25 at 10 49 56" src="https://user-images.githubusercontent.com/797801/35384566-8f5cd82e-01bd-11e8-9258-9c03036d5262.png">

**Comment by jayfk** [comment]
Hi!

The bot looks on the metadata that's available on PyPi to determine if the project is Python 3 compatible: https://pypi.python.org/pypi/scp/json

The classifier list for scp is empty on PyPi. It could be that the setup.py was modified after the most recent release, so the classifiers from setup.py haven't made it into PyPi's metadata. 

I can add this to a whitelist in pyup.io's backend, but the best thing would be to raise this issue with scp so that they can update the metadata accordingly.

**Comment by DEKHTIARJonathan** [comment]
Hello @jayfk,

I have the same issue with the package: [untangle](https://pypi.python.org/pypi/untangle)

If you have a look to the classifiers published in the package on PyPI you have the followings:

```
classifiers=(
        'Development Status :: 5 - Production/Stable',
        'Intended Audience :: Developers',
        'Natural Language :: English',
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python',
        'Programming Language :: Python :: 2.6',
        'Programming Language :: Python :: 2.7',
        "Programming Language :: Python :: 3.3",
        "Programming Language :: Python :: 3.4",
        "Programming Language :: Python :: 3.5",
        "Programming Language :: Python :: 3.6",
    ),
```

Inside the PKG_INFO file:
```
Classifier: Programming Language :: Python
Classifier: Programming Language :: Python :: 2.6
Classifier: Programming Language :: Python :: 2.7
Classifier: Programming Language :: Python :: 3.3
Classifier: Programming Language :: Python :: 3.4
Classifier: Programming Language :: Python :: 3.5
Classifier: Programming Language :: Python :: 3.6
```

**Comment by jayfk** [comment]
@DEKHTIARJonathan the problem is that this isn't on PyPi. If you take a look at the JSON here https://pypi.python.org/pypi/untangle/json you'll see that the classifiers are empty.

Please report this to the people maintaining the package and tell them to republish it. Once the classifiers are set, it will work :)

**Comment by DEKHTIARJonathan** [comment]
That's weird... Why is it unpublished ? It is inside the setup.py and PKG INFO file ...

**Comment by jayfk** [comment]
Well, it is published but the classifiers are missing. Probably because they were added to `setup.py` after the release was pushed to PyPi.
