### ISSUE TITLE
Ignore/skip specific dependencies

### ISSUE THREAD

**Issue by Osmose** [pyupio/pyup#273]
I couldn't find any documentation anywhere for this: Is it possible to mark a specific requirement as ignored so that the PR bot does not try to update it? We've got a few dependencies that are stuck on old versions for now, and each time the bot makes a PR (we do monthly) I have to update it to revert the upgrades to those dependencies manually.

**Comment by jayfk** [comment]
Sure, just use the `# pyup: ignore` filter.

For example, if you don't want to receive updates for flask: `flask==0.11 # pyup: ignore`. 

More on this here: https://pyup.io/docs/bot/filter/

**Comment by Osmose** [comment]
Thanks for the info!

I just realized I copied a comment like that from another requirements file in our org and we're still receiving updates from the bot. The relevant line is here: https://github.com/mozilla-services/socorro/blob/master/requirements/default.txt#L85

Is our formatting wrong? Is the space after the colon significant? Could the inclusion of hashes be breaking it instead?

**Comment by jayfk** [comment]
> Could the inclusion of hashes be breaking it instead?

This could very well be the case. It should work, there's even a test for it here: https://github.com/pyupio/pyup/blob/master/tests/test_requirements.py#L157-L178

Due to some packaging foo that's going on internally the comment probably disappears at some place. 

I won't have time to look into this today, but I'll make sure to get back to you on this on monday!

**Comment by jayfk** [comment]
This should work now.

**Comment by Osmose** [comment]
Thanks! :D
