### ISSUE TITLE
Add gitlab support

### ISSUE THREAD

**Issue by jayfk** [pyupio/pyup#55]

**Comment by jayfk** [comment]
Thanks to @managai this is now possible using the bot from the command line!

**Comment by LuisAlejandro** [comment]
Where's the reference for this? How can be achieved?

**Comment by goetzb** [comment]
Fyi @LuisAlejandro - you probably already found that yourself by now as well. Since I did also not find this on the website, but was interested in the status of the GitLab support, I looked a bit further and found the GitLab integration documented on https://github.com/pyupio/pyup and http://pyup.readthedocs.io/en/latest/readme.html#run-your-first-update

Maybe it's not on the website yet, because it's still "experimental".
